export { ClientService } from './clientService'
export { InvoiceService } from './invoiceService'
export { DocumentService } from './documentService'
export { ComplianceService } from './complianceService'
export { EmployeeService } from './employeeService'
export { DashboardService } from './dashboardService'
export { TaskService } from './taskService'
export { PaymentService } from './paymentService'
export { ReportService } from './reportService'
export { AuthService } from './authService'
export { SearchService } from './searchService'
export { SettingsService } from './settingsService'
export { CompanyService, NotificationService, ChatService, CalendarService, ActivityService } from './miscService'
export { NoteService } from './noteService'
export { AIService } from './aiService'
export type { AIResult, AIChatMessage } from './aiService'
